"""UNKNOWN takes the whole library, so the gate must be told who this is.

MEASURED. `patterns_for` was repaired to use positive model applicability, and
the repair could not fire: `_patterns_for_company` asked `profile_for` for a
classification while passing only a company NAME. Meta and Amazon are not in
the curated 100-company manifest, so both resolved to UNKNOWN, UNKNOWN takes
all twelve patterns, and Meta was handed `capacity_ahead_of_demand` — which
is how an advertising platform came to be told about take-or-pay terms and
ageing production lines.

The applicability logic was never the whole defect. The caller was.
"""
import ast
import pathlib

import pytest

from intent_engine.company_ingestion.service import (
    _patterns_for_company, _subject_evidence_text,
)
from intent_engine.executive.company_profile import MODEL_CLASSES
from intent_engine.strategic_intelligence.patterns import PATTERN_LIBRARY

SERVICE = (pathlib.Path(__file__).resolve().parents[1]
           / "src/intent_engine/company_ingestion/service.py")

META_SIC = {"sic": "7370",
            "sic_description": "SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING"}
AMAZON_SIC = {"sic": "5961",
              "sic_description": "RETAIL-CATALOG & MAIL-ORDER HOUSES"}

META_FILING = (
    "Item 1. Business. We generate substantially all of our revenue from "
    "selling advertising placements to marketers. Our advertising revenue "
    "is generated by displaying ad products on Facebook, Instagram, "
    "Messenger and third-party affiliated websites or mobile applications."
)
AMAZON_FILING = (
    "Item 1. Business. We have organized our operations into three "
    "reportable segments: North America, International, and Amazon Web "
    "Services (AWS). Our online stores and physical stores serve consumers "
    "through our retail segment, while AWS provides cloud infrastructure "
    "services to enterprises and developers."
)


def _ids(patterns):
    return {p.pattern_id if hasattr(p, "pattern_id") else p["pattern_id"]
            for p in patterns}


# --- the defect, stated as a test ---------------------------------------

def test_name_alone_still_falls_back_to_the_whole_library():
    """The old behaviour, kept explicit. This is not a regression to fix in
    the gate — it is the reason the CALL SITE must supply more."""
    assert len(_ids(_patterns_for_company("Meta Platforms"))) == \
        len(PATTERN_LIBRARY)


def test_meta_is_classified_from_its_own_revenue_sentence():
    patterns = _ids(_patterns_for_company(
        "Meta Platforms", domain="meta.com", registrant=META_SIC,
        evidence_text=META_FILING))
    assert len(patterns) < len(PATTERN_LIBRARY)
    # THE SENTENCE THAT REACHED A CHIEF EXECUTIVE. An advertising platform
    # has no order book and no production line.
    assert "capacity_ahead_of_demand" not in patterns


def test_amazon_is_not_walmart():
    """Both are SIC-classified as retail. Only Amazon's own filing says it
    runs a cloud infrastructure engine alongside a commerce engine."""
    amazon = _ids(_patterns_for_company(
        "Amazon.com", domain="amazon.com", registrant=AMAZON_SIC,
        evidence_text=AMAZON_FILING))
    walmart = _ids(_patterns_for_company(
        "Walmart", domain="walmart.com",
        registrant={"sic": "5331", "sic_description": "RETAIL-VARIETY STORES"},
        evidence_text="Item 1. Business. We operate retail stores."))
    assert amazon != walmart, "one class for two different economies"
    assert len(amazon) < len(PATTERN_LIBRARY)


def test_an_unrelated_model_keeps_its_own_smaller_set():
    """Older classes are unchanged by the repair."""
    exxon = _ids(_patterns_for_company(
        "Exxon Mobil", domain="exxonmobil.com",
        registrant={"sic": "2911", "sic_description": "PETROLEUM REFINING"}))
    caterpillar = _ids(_patterns_for_company(
        "Caterpillar", domain="caterpillar.com",
        registrant={"sic": "3531",
                    "sic_description": "CONSTRUCTION MACHINERY & EQUIP"}))
    assert exxon != caterpillar
    assert len(exxon) < len(PATTERN_LIBRARY)
    assert len(caterpillar) < len(PATTERN_LIBRARY)


def test_no_registered_model_class_silently_takes_every_pattern():
    """A class that qualifies for the whole library is indistinguishable
    from a class nobody wrote applicability for — which is exactly how the
    three newest classes inherited 12/12."""
    from intent_engine.strategic_intelligence.patterns import patterns_for
    inheriting = [m for m in MODEL_CLASSES
                  if len(_ids(patterns_for(m))) == len(PATTERN_LIBRARY)]
    assert inheriting == [], inheriting


# --- the subject-only rule ----------------------------------------------

def test_a_competitor_filing_cannot_classify_this_company():
    documents = [
        {"final_url": "https://www.sec.gov/Archives/edgar/data/1326801/x/a.htm",
         "source_class": "investor_material", "text_content": "our own text"},
        {"final_url": "https://www.sec.gov/Archives/edgar/data/789019/y/b.htm",
         "source_class": "investor_material",
         "text_content": "WE GENERATE REVENUE FROM ADVERTISING"},
        {"final_url": "https://example.com/rival",
         "source_class": "competitor",
         "text_content": "RIVAL ADVERTISING REVENUE"},
    ]
    text = _subject_evidence_text(documents, cik="0001326801")
    assert "our own text" in text
    assert "789019" not in text and "WE GENERATE REVENUE FROM" not in text
    assert "RIVAL ADVERTISING REVENUE" not in text


def test_no_cik_keeps_the_companys_own_pages_and_drops_the_rest():
    """`source_class` is the closed vocabulary in
    company_ingestion.records.SOURCE_CLASSES — "product" is a source_TYPE and
    a real document can never carry it, so this fixture uses the classes
    production actually assigns."""
    documents = [{"final_url": "https://acme.com/a",
                  "source_class": "company_owned", "text_content": "alpha"},
                 {"final_url": "https://acme.com/ir",
                  "source_class": "investor_material",
                  "text_content": "gamma"},
                 {"final_url": "https://rival.com/b",
                  "source_class": "competitor", "text_content": "beta"},
                 {"final_url": "https://press.example/c",
                  "source_class": "independent_reporting",
                  "text_content": "delta"}]
    text = _subject_evidence_text(documents, cik="")
    assert "alpha" in text and "gamma" in text
    assert "beta" not in text and "delta" not in text


def test_an_unrecognised_source_class_fails_closed():
    """Ownership is the one question where an unknown answer must not be
    read as "yes". A class nobody has decided about is not the subject's
    voice."""
    text = _subject_evidence_text(
        [{"final_url": "https://acme.com/a",
          "source_class": "something_new", "text_content": "alpha"}], cik="")
    assert "alpha" not in text


# --- the seam: the call site must actually pass them --------------------

def test_the_report_call_site_supplies_the_classification_inputs():
    """A FIX WITH NO CALLER STAYS GREEN. Every parameter added above is
    optional and defaults to the old behaviour, so the only thing that makes
    this repair real is the call site — asserted structurally rather than by
    running a live report, because the failure mode is silence."""
    tree = ast.parse(SERVICE.read_text())
    calls = [n for n in ast.walk(tree)
             if isinstance(n, ast.Call)
             and isinstance(n.func, ast.Name)
             and n.func.id == "_patterns_for_company"]
    assert calls, "the pattern gate is no longer called at all"
    for call in calls:
        supplied = {kw.arg for kw in call.keywords}
        missing = {"domain", "registrant", "evidence_text"} - supplied
        assert not missing, (
            f"the pattern gate is called without {sorted(missing)}, so every "
            "company outside the manifest resolves to UNKNOWN and takes the "
            "whole library")


@pytest.mark.parametrize("name", ["_registrant_for", "_subject_evidence_text"])
def test_the_inputs_have_a_producer(name):
    source = SERVICE.read_text()
    tree = ast.parse(source)
    defined = {n.name for n in ast.walk(tree)
               if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef))}
    assert name in defined
