"""What a company is probably DOING, inferred from what it was seen to do.

THE MODELLING CHOICE THAT MATTERS
---------------------------------
A company's strategic posture is not observable. Its actions are. So this
module keeps a probability distribution over postures and moves mass between
them as evidence arrives — it never elects a winner.

That is not a stylistic preference. "Microsoft is defending its position" is a
sentence a reader will act on; `P(DEFENDING)=0.41, P(MARKET_SHARE_SEEKING)=
0.33, P(COST_CUTTING)=0.26` is a sentence a reader will investigate. The first
is almost always overstated, because the same observable action is generated by
several postures, and the evidence usually cannot separate them.

WHY A DISTRIBUTION AND NOT A LABEL
----------------------------------
A price cut is consistent with seeking share, with excess capacity, with weak
demand, with deterring entry, and with a bundling push. Any code path that
picks one has invented the four it discarded. `observe` therefore takes a
*likelihood over states* — how well each posture explains the action — and the
posterior falls out of that, keeping every rival alive with its own mass.

CERTAINTY IS STRUCTURALLY UNREACHABLE
-------------------------------------
`_CEIL` caps any single state below 1.0 and `assert_uncertain` is available to
callers that render. There is no code path that produces "this company is
certainly X", because the underlying evidence never justifies it.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, replace
from typing import Dict, Optional, Sequence, Tuple

from . import micro_evidence as ME

CONTRACT_VERSION = "hidden_state.v1"

GROWING = "GROWING"
DEFENDING = "DEFENDING"
EXPANDING = "EXPANDING"
COST_CUTTING = "COST_CUTTING"
CAPITAL_CONSTRAINED = "CAPITAL_CONSTRAINED"
PREPARING_ACQUISITION = "PREPARING_ACQUISITION"
PREPARING_DIVESTITURE = "PREPARING_DIVESTITURE"
PRICE_AGGRESSIVE = "PRICE_AGGRESSIVE"
CAPACITY_CONSTRAINED = "CAPACITY_CONSTRAINED"
WAITING = "WAITING"
EXPERIMENTING = "EXPERIMENTING"
REGULATORY_DEFENSIVE = "REGULATORY_DEFENSIVE"
PLATFORM_EXPANDING = "PLATFORM_EXPANDING"
SERVICES_DEPENDENT = "SERVICES_DEPENDENT"
PRODUCTIZING = "PRODUCTIZING"
MARKET_SHARE_SEEKING = "MARKET_SHARE_SEEKING"
MARGIN_PROTECTING = "MARGIN_PROTECTING"

STATES = (GROWING, DEFENDING, EXPANDING, COST_CUTTING, CAPITAL_CONSTRAINED,
          PREPARING_ACQUISITION, PREPARING_DIVESTITURE, PRICE_AGGRESSIVE,
          CAPACITY_CONSTRAINED, WAITING, EXPERIMENTING, REGULATORY_DEFENSIVE,
          PLATFORM_EXPANDING, SERVICES_DEPENDENT, PRODUCTIZING,
          MARKET_SHARE_SEEKING, MARGIN_PROTECTING)

# No posterior may reach 1.0. A latent posture inferred from public actions is
# never certain, and a renderer that received 1.0 would write "is", not
# "probably is".
_CEIL = 0.90
_FLOOR = 0.001


class HiddenStateError(ValueError):
    """A hidden-state operation that would have asserted certainty."""


@dataclass(frozen=True)
class StateObservation:
    """One recorded movement of the distribution."""
    at: str
    action: str
    prior: Tuple[Tuple[str, float], ...]
    posterior: Tuple[Tuple[str, float], ...]
    evidence_ids: Tuple[str, ...]
    alternative_states: Tuple[str, ...]
    invalidating_evidence: str
    uncertainty: float

    def moved(self, top_n: int = 3) -> Tuple[Tuple[str, float, float], ...]:
        """(state, before, after) for the states that actually moved."""
        before = dict(self.prior)
        deltas = [(s, before.get(s, 0.0), p) for s, p in self.posterior]
        deltas.sort(key=lambda t: abs(t[2] - t[1]), reverse=True)
        return tuple(d for d in deltas[:top_n] if abs(d[2] - d[1]) >= 0.005)

    def as_dict(self) -> dict:
        return {"at": self.at, "action": self.action,
                "prior": dict(self.prior), "posterior": dict(self.posterior),
                "evidence_ids": list(self.evidence_ids),
                "alternative_states": list(self.alternative_states),
                "invalidating_evidence": self.invalidating_evidence,
                "uncertainty": self.uncertainty,
                "moved": [{"state": s, "from": a, "to": b}
                          for s, a, b in self.moved()]}


@dataclass(frozen=True)
class HiddenStateBelief:
    """A posterior over postures for one company."""
    subject: str
    distribution: Tuple[Tuple[str, float], ...]
    last_updated: str
    history: Tuple[StateObservation, ...] = ()

    @property
    def as_map(self) -> Dict[str, float]:
        return dict(self.distribution)

    @property
    def entropy(self) -> float:
        """How undecided the distribution is. Higher means less committed."""
        return round(-sum(p * math.log2(p) for _, p in self.distribution
                          if p > 0), 4)

    @property
    def leading(self) -> Tuple[str, float]:
        state, p = max(self.distribution, key=lambda kv: kv[1])
        return state, p

    def top(self, n: int = 3) -> Tuple[Tuple[str, float], ...]:
        return tuple(sorted(self.distribution, key=lambda kv: kv[1],
                            reverse=True)[:n])

    def as_dict(self) -> dict:
        state, p = self.leading
        return {"subject": self.subject, "distribution": self.as_map,
                "top": [{"state": s, "probability": v} for s, v in self.top()],
                "leading_state": state, "leading_probability": p,
                "entropy": self.entropy, "last_updated": self.last_updated,
                "certainty_capped_at": _CEIL,
                "history": [h.as_dict() for h in self.history]}


def uniform(subject: str, *, at: str,
            states: Sequence[str] = STATES) -> HiddenStateBelief:
    """Start undecided. The honest prior when nothing has been observed."""
    p = round(1.0 / len(states), 6)
    return HiddenStateBelief(subject=subject,
                             distribution=tuple((s, p) for s in states),
                             last_updated=at[:10])


def seeded(subject: str, *, at: str, prior: Dict[str, float],
           states: Sequence[str] = STATES) -> HiddenStateBelief:
    """Start from an informed prior over a NAMED SUBSET of postures.

    Uniform-over-seventeen is the right prior when nothing is known, but it
    makes every posterior look weak: one strong observation moves the leader
    to about 15%, which reads as "no idea" even when the evidence was good.
    Most real subjects are not that blank — a company with public filings has
    already narrowed the field.

    States omitted from `prior` are not deleted. They keep a small residual
    share of the remaining mass, because a posture nobody thought to list is
    exactly the one that turns out to be right.
    """
    if not prior:
        raise HiddenStateError("a seeded prior needs at least one state")
    unknown = set(prior) - set(states)
    if unknown:
        raise HiddenStateError(f"unknown states in prior: {sorted(unknown)}")
    named = {s: max(float(p), 0.0) for s, p in prior.items()}
    total_named = sum(named.values())
    if total_named <= 0:
        raise HiddenStateError("a seeded prior cannot be all zeros")
    # Reserve a fifth of the mass for the postures nobody named.
    residual_share = 0.20
    others = [s for s in states if s not in named]
    scaled = {s: (p / total_named) * (1 - residual_share if others else 1.0)
              for s, p in named.items()}
    if others:
        each = residual_share / len(others)
        scaled.update({s: each for s in others})
    return HiddenStateBelief(
        subject=subject, distribution=tuple(sorted(
            _renormalise(scaled).items())), last_updated=at[:10])


def observe(belief: HiddenStateBelief, *, action: str,
            likelihoods: Dict[str, float], at: str,
            evidence_ids: Sequence[str] = (),
            invalidating_evidence: str = "") -> HiddenStateBelief:
    """Move mass by how well each posture explains the observed action.

    `likelihoods` is P(action | state) — relative, not normalised. States the
    caller does not mention keep a neutral likelihood, which is what stops an
    unmentioned rival from being silently eliminated.

    Requires at least two states with distinct likelihoods: an action that
    every posture explains equally is not evidence about posture, and an
    action the caller claims only one posture could produce is almost always
    the caller having stopped thinking.
    """
    if not likelihoods:
        raise HiddenStateError("an observation with no likelihoods cannot "
                               "move a distribution")
    distinct = {round(v, 6) for v in likelihoods.values()}
    if len(likelihoods) < 2 or len(distinct) < 2:
        raise HiddenStateError(
            "a hidden-state observation needs at least two states with "
            "different likelihoods; a single-state claim asserts certainty "
            "about a latent posture that public evidence cannot support")

    prior = belief.as_map
    raw = {s: prior.get(s, 0.0) * float(likelihoods.get(s, 1.0))
           for s in prior}
    total = sum(raw.values())
    if total <= 0:
        raise HiddenStateError("likelihoods eliminated every state; a "
                               "posterior of zero everywhere is not a belief")
    posterior = _renormalise({s: v / total for s, v in raw.items()})

    alternatives = tuple(s for s, _ in sorted(
        posterior.items(), key=lambda kv: kv[1], reverse=True)[1:4])
    record = StateObservation(
        at=at[:10], action=action,
        prior=tuple(sorted(prior.items())),
        posterior=tuple(sorted(posterior.items())),
        evidence_ids=tuple(evidence_ids),
        alternative_states=alternatives,
        invalidating_evidence=invalidating_evidence,
        uncertainty=round(-sum(p * math.log2(p) for p in posterior.values()
                               if p > 0), 4))
    return replace(belief, distribution=tuple(sorted(posterior.items())),
                   last_updated=at[:10], history=belief.history + (record,))


def _renormalise(dist: Dict[str, float]) -> Dict[str, float]:
    """Enforce the certainty cap, then renormalise so it still sums to 1.

    The cap is applied by redistributing the excess across the other states in
    proportion to their existing mass, so capping does not silently promote
    whichever rival happens to be alphabetically first.
    """
    capped = {s: min(max(p, _FLOOR), _CEIL) for s, p in dist.items()}
    total = sum(capped.values())
    if total <= 0:  # pragma: no cover - guarded upstream
        raise HiddenStateError("degenerate distribution")
    return {s: round(p / total, 6) for s, p in capped.items()}


def assert_uncertain(belief: HiddenStateBelief) -> None:
    """Raise if any state has been asserted as certain.

    Called by the renderer path. A break proof drives a distribution to a
    single state and expects this to fire.
    """
    for state, p in belief.distribution:
        if p > _CEIL + 1e-6:
            raise HiddenStateError(
                f"{belief.subject}: P({state})={p} exceeds the certainty cap "
                f"{_CEIL}; a latent posture inferred from public action may "
                f"not be asserted as certain")


def describe(belief: HiddenStateBelief) -> str:
    """Founder-readable phrasing that keeps the rivals visible."""
    top = belief.top(2)
    if not top:  # pragma: no cover
        return "No posture evidence."
    lead, p = top[0]
    text = (f"The evidence most consistent with "
            f"{_HUMAN.get(lead, lead.lower().replace('_', ' '))} "
            f"({p:.0%} of the weight)")
    if len(top) > 1:
        second, q = top[1]
        text += (f", though {_HUMAN.get(second, second.lower().replace('_', ' '))} "
                 f"remains live at {q:.0%}")
    return text + "."


_HUMAN = {
    GROWING: "growing the business", DEFENDING: "defending a position",
    EXPANDING: "expanding into new ground", COST_CUTTING: "cutting cost",
    CAPITAL_CONSTRAINED: "operating under a capital constraint",
    PREPARING_ACQUISITION: "preparing an acquisition",
    PREPARING_DIVESTITURE: "preparing a divestiture",
    PRICE_AGGRESSIVE: "competing aggressively on price",
    CAPACITY_CONSTRAINED: "running into a capacity limit",
    WAITING: "deliberately waiting", EXPERIMENTING: "experimenting",
    REGULATORY_DEFENSIVE: "managing regulatory exposure",
    PLATFORM_EXPANDING: "expanding a platform",
    SERVICES_DEPENDENT: "leaning on services revenue",
    PRODUCTIZING: "turning services into product",
    MARKET_SHARE_SEEKING: "buying market share",
    MARGIN_PROTECTING: "protecting margin",
}


def summarise(before: Sequence[HiddenStateBelief],
              after: Sequence[HiddenStateBelief]) -> dict:
    """Posterior changes by company, for the session report."""
    prior = {b.subject: b.as_map for b in before}
    changes = []
    for belief in after:
        was = prior.get(belief.subject)
        if not was:
            continue
        moved = [{"state": s, "from": round(was.get(s, 0.0), 4),
                  "to": round(p, 4)}
                 for s, p in belief.distribution
                 if abs(p - was.get(s, 0.0)) >= 0.01]
        if moved:
            changes.append({"subject": belief.subject,
                            "moved": sorted(
                                moved,
                                key=lambda m: abs(m["to"] - m["from"]),
                                reverse=True)[:4],
                            "entropy": belief.entropy})
    return {"companies_tracked": len(after), "companies_moved": len(changes),
            "changes": changes}
