"""Extract the sections of an annual report that carry competitive evidence.

THE MEASURED PROBLEM THIS SOLVES
--------------------------------
Competitor intelligence rendered as a stated absence on all five validation
companies last cycle. The extractor was not at fault — given real filing text
it finds named rivals, the consulting alternative and the in-house build, and
it refuses compensation peer groups. Its INPUT was empty.

A 10-Q carries no Competition section. That lives in Item 1. Business of the
10-K, and the 10-K was deprioritised because its primary document routinely
runs past the 2,000,000-byte fetch cap, so the whole response was discarded.

The premise behind that deprioritisation turns out to be wrong in the way that
matters. An annual report is an ORDERED document: Item 1 is at the front, and
truncation removes the end. Measured 2026-08-05 against the latest filed 10-K:

    Palantir     Competition text at char  65k of 555k retrieved
    Shopify                            38k of 411k
    Caterpillar                       154k of 351k
    Nvidia                             35k of 373k (fits whole, no truncation)

So the first 2MB reaches the competitive material every time. The fix is to
keep the truncated document rather than discard it — and to carry the
truncation forward honestly.

TRUNCATION IS NEVER SILENTLY COMPLETE
-------------------------------------
`AnnualFilingSections.truncated` propagates to every extracted section, and
`completeness_note` states what was and was not read. A section whose heading
was found but whose text ran past the cut is marked `INCOMPLETE`, because a
half-read Competition section that looks whole would understate the field —
the rivals a company lists last are the ones it takes least seriously, and
their absence changes the reading.

WHY REGEX AND NOT A PARSER
--------------------------
Filing HTML is generated by a dozen vendors with no shared structure; the only
reliable landmarks are the statutory item headings themselves, which are
mandated by Regulation S-K and appear in every filing. Matching those is
robust in a way that matching markup is not.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Sequence, Tuple

CONTRACT_VERSION = "annual_filing_sections.v1"

COMPLETE = "COMPLETE"
INCOMPLETE = "INCOMPLETE"
ABSENT = "ABSENT"

# Statutory headings, in filing order. Mandated by Regulation S-K, which is
# why they are dependable landmarks where markup is not. 20-F and 40-F use
# different numbering, so their equivalents are listed alongside.
_ITEM_PATTERNS: Tuple[Tuple[str, str], ...] = (
    ("business", r"item\s*1\s*[.\-—:]?\s*business\b"),
    ("risk_factors", r"item\s*1a\s*[.\-—:]?\s*risk\s+factors\b"),
    ("unresolved_staff", r"item\s*1b\s*[.\-—:]?\s*unresolved\b"),
    ("properties", r"item\s*2\s*[.\-—:]?\s*propert"),
    ("legal", r"item\s*3\s*[.\-—:]?\s*legal\s+proceedings\b"),
    ("mdna", r"item\s*7\s*[.\-—:]?\s*management.{0,3}s\s+discussion\b"),
)

# The Competition subsection inside Item 1. Filers phrase the heading several
# ways; all of them start the same paragraph.
#
# The lookahead is load-bearing. Matching the bare word finds it in prose —
# Palantir's Item 1 says "raise the barriers to entry for competition." long
# before any competitive discussion, and starting the section there returned
# 19,000 characters beginning mid-sentence. A heading is followed by the
# start of new prose (a capitalised word), never by sentence-ending
# punctuation, so requiring that separates the two.
_COMPETITION_HEADING = re.compile(
    r"\b(competition|competitive\s+(?:landscape|environment|conditions|"
    r"strengths|factors)|our\s+competitors?)\b(?=\s+[A-Z(])", re.I)

# Among the matches that survive the lookahead, a capitalised one is the
# actual heading and a lowercase one is prose that happens to fit.
#
# Requiring a sentence-ending preceder was tried and is wrong: filing text
# carries page furniture, so Shopify's genuine "Competition" heading is
# preceded by "10 Table of Contents" rather than by a full stop, and the
# check discarded the real heading on two of three filings.
_CAPITALISED_HEADING = re.compile(r"^(Competition|Competitive|Our Competitor)")

# Where the Competition discussion ends: the next Item heading, or one of the
# subsections that conventionally follows it inside Item 1.
_COMPETITION_END = re.compile(
    r"\b(item\s*1a\b|risk\s+factors\b|human\s+capital\b|employees\b|"
    r"intellectual\s+property\b|government\s+regulation\b|"
    r"available\s+information\b|corporate\s+information\b)", re.I)

# A 10-K's table of contents repeats every heading before any body text, so
# every heading matches at least twice and the first match is the wrong one.
#
# A fixed front-zone cutoff does not work: measured on Palantir's 2026 10-K
# the contents page sits at char 27,000 — after a long cover page — and the
# real Item 1 heading at 35,764. Any constant large enough to skip that
# contents page would skip real headings in a shorter filing.
#
# What separates them reliably is what FOLLOWS. A contents entry is followed
# by a page number and the next entry ("Business 4 Item 1A. Risk Factors 12");
# a body heading is followed by prose. So a match with another item heading
# close behind it is a contents line.
_TOC_LOOKAHEAD_CHARS = 90
_TOC_NEIGHBOUR = re.compile(r"item\s*\d+[ab]?\s*[.\-—:]", re.I)

_MIN_SECTION_CHARS = 200


@dataclass(frozen=True)
class FilingSection:
    """One extracted section, with its completeness stated."""
    name: str
    text: str
    status: str
    start_char: int
    note: str = ""

    @property
    def usable(self) -> bool:
        return self.status in (COMPLETE, INCOMPLETE) and bool(self.text)

    def as_dict(self) -> dict:
        return {"name": self.name, "status": self.status,
                "chars": len(self.text), "start_char": self.start_char,
                "note": self.note}


@dataclass(frozen=True)
class AnnualFilingSections:
    """The competitive material an annual report actually yielded."""
    form: str
    source_url: str
    filed_at: str
    truncated: bool
    retrieved_chars: int
    sections: Tuple[FilingSection, ...] = ()

    def section(self, name: str) -> Optional[FilingSection]:
        for s in self.sections:
            if s.name == name:
                return s
        return None

    @property
    def competition(self) -> Optional[FilingSection]:
        return self.section("competition")

    @property
    def completeness_note(self) -> str:
        """What was read, and what was not. Never implies more than it read."""
        if not self.truncated:
            return (f"The full {self.form} primary document was retrieved "
                    f"({self.retrieved_chars:,} characters of text).")
        found = [s.name for s in self.sections if s.usable]
        note = (f"The {self.form} exceeded the retrieval cap, so the first "
                f"{self.retrieved_chars:,} characters were read and the "
                f"remainder was not.")
        if found:
            note += (f" That covered: {', '.join(sorted(found))}. Sections "
                     f"later in the document were not read, and their absence "
                     f"here is a limit of retrieval, not a finding about the "
                     f"company.")
        return note

    def as_dict(self) -> dict:
        return {"contract": CONTRACT_VERSION, "form": self.form,
                "source_url": self.source_url, "filed_at": self.filed_at,
                "truncated": self.truncated,
                "retrieved_chars": self.retrieved_chars,
                "completeness_note": self.completeness_note,
                "sections": [s.as_dict() for s in self.sections]}


def to_text(html: str) -> str:
    """Strip markup to readable text, preserving word boundaries.

    Tags become spaces rather than being deleted: deleting them welds
    `</td><td>Palantir` into `Palantir` glued to the previous cell's last
    word, and the competitor finder then fails to match a company name it
    can plainly see.
    """
    text = re.sub(r"(?is)<(script|style)[^>]*>.*?</\1>", " ", html or "")
    text = re.sub(r"<[^>]+>", " ", text)
    text = (text.replace("&nbsp;", " ").replace("&amp;", "&")
            .replace("&#8217;", "'").replace("&#8220;", '"')
            .replace("&#8221;", '"').replace("&#39;", "'")
            .replace("&lt;", "<").replace("&gt;", ">"))
    return re.sub(r"\s+", " ", text).strip()


def extract(html_or_text: str, *, form: str = "10-K", source_url: str = "",
            filed_at: str = "", truncated: bool = False
            ) -> AnnualFilingSections:
    """Pull the competitively-relevant sections out of an annual report."""
    text = to_text(html_or_text) if "<" in (html_or_text or "")[:2000] \
        else re.sub(r"\s+", " ", html_or_text or "").strip()
    sections: List[FilingSection] = []

    bounds = _item_bounds(text)
    for name, (start, end) in bounds.items():
        body = text[start:end].strip()
        if len(body) < _MIN_SECTION_CHARS:
            continue
        # A section that runs to the very end of a truncated document was
        # almost certainly cut mid-way.
        status = INCOMPLETE if (truncated and end >= len(text) - 1) \
            else COMPLETE
        sections.append(FilingSection(
            name=name, text=body, status=status, start_char=start,
            note="ran past the retrieval cut" if status == INCOMPLETE else ""))

    competition = _extract_competition(text, bounds, truncated)
    if competition is not None:
        sections.append(competition)

    return AnnualFilingSections(
        form=form, source_url=source_url, filed_at=filed_at,
        truncated=truncated, retrieved_chars=len(text),
        sections=tuple(sections))


def _item_bounds(text: str) -> Dict[str, Tuple[int, int]]:
    """Locate each statutory item, skipping the table of contents.

    Every heading appears twice — once in the contents, once as the section.
    The contents copy comes first and is followed by a page number, so the
    LAST match inside the front zone is the real heading in practice; taking
    the first yields a page of dotted leaders.
    """
    hits: List[Tuple[int, str]] = []
    for name, pattern in _ITEM_PATTERNS:
        matches = [(m.start(), m.end())
                   for m in re.finditer(pattern, text, re.I)]
        if not matches:
            continue
        body = [s for s, e in matches
                if not _TOC_NEIGHBOUR.search(
                    text[e:e + _TOC_LOOKAHEAD_CHARS])]
        hits.append((body[0] if body else matches[-1][0], name))

    hits.sort()
    bounds: Dict[str, Tuple[int, int]] = {}
    for i, (start, name) in enumerate(hits):
        end = hits[i + 1][0] if i + 1 < len(hits) else len(text)
        bounds[name] = (start, end)
    return bounds


def _extract_competition(text: str, bounds: Dict[str, Tuple[int, int]],
                         truncated: bool) -> Optional[FilingSection]:
    """The Competition discussion inside Item 1. Business.

    Scoped to Item 1 deliberately. The word "competition" appears throughout
    a 10-K — in risk factors, in MD&A, in the legal proceedings — and taking
    any occurrence would return a risk-factor paragraph that names no rival,
    which reads to the finder as "no competitors found".
    """
    if "business" not in bounds:
        return None
    b_start, b_end = bounds["business"]
    window = text[b_start:b_end]
    candidates = list(_COMPETITION_HEADING.finditer(window))
    if not candidates:
        return None
    # A capitalised match is the heading; fall back to the first surviving
    # match when the filer set the heading in some other case.
    match = next((c for c in candidates
                  if _CAPITALISED_HEADING.match(c.group(0))), candidates[0])

    start = match.start()
    tail = window[start + len(match.group(0)):]
    end_match = _COMPETITION_END.search(tail)
    end = (start + len(match.group(0)) + end_match.start()) if end_match \
        else len(window)
    body = window[start:end].strip()
    if len(body) < _MIN_SECTION_CHARS:
        # A bare heading with no discussion behind it: the section exists but
        # the text was cut. Reported, not silently dropped.
        return FilingSection(
            name="competition", text=body,
            status=INCOMPLETE if truncated else ABSENT,
            start_char=b_start + start,
            note="the Competition heading was found but its discussion was "
                 "not retrieved")
    status = COMPLETE
    note = ""
    if end_match is None and truncated:
        status = INCOMPLETE
        note = ("the Competition discussion ran past the retrieval cut, so "
                "rivals named later in it were not read")
    return FilingSection(name="competition", text=body, status=status,
                         start_char=b_start + start, note=note)


def assert_not_presented_as_complete(sections: AnnualFilingSections,
                                     rendered: str) -> None:
    """Refuse text that presents a truncated filing as a full one.

    Checked on the way out. A renderer that wrote "the company's annual
    report lists three competitors" from a truncated Competition section
    would be making a completeness claim the retrieval cannot support, and
    that claim is exactly as citable and exactly as wrong.
    """
    if not sections.truncated:
        return
    banned = ("the full annual report", "the complete 10-k",
              "the entire filing", "all competitors named",
              "the company names exactly", "its only competitors")
    low = (rendered or "").lower()
    for phrase in banned:
        if phrase in low:
            raise ValueError(
                f"text claims completeness ({phrase!r}) from a TRUNCATED "
                f"filing; the retrieval read {sections.retrieved_chars:,} "
                f"characters and stopped, so a completeness claim is not "
                f"supported")
